export type LandingLang = 'pt' | 'en';

export const landingCopy = {
  pt: {
    wordmark: 'FaturaFlow',
    navComo: 'Como funciona',
    navPreco: 'Preço',
    navEntrar: 'Entrar',
    navComecar: 'Começar',
    h1: 'Deixe o IVA dos recibos pronto para o contabilista',
    sub: 'Carregue faturas e recibos portugueses. Obtenha uma estimativa de IVA e um pacote organizado para enviar.',
    ctaPrimary: 'Começar com um recibo',
    ctaSecondary: 'Ver como funciona',
    howTitle: 'Como funciona',
    how1Title: 'Carregar',
    how1Body: 'PDF ou foto',
    how2Title: 'Estimar IVA',
    how2Body: 'Linhas e taxa quando possível',
    how3Title: 'Pacote',
    how3Body: 'Ficheiros prontos para o contabilista',
    receiveTitle: 'O que recebe',
    receive1: 'Estimativa de IVA por documento (quando legível)',
    receive2: 'Lista organizada dos documentos',
    receive3: 'Pacote para reenviar ao contabilista',
    whoTitle: 'Para quem',
    whoBody:
      'Quem junta recibos à mão e perde tempo antes de enviar ao contabilista. Micro-empresas, freelancers, e quem ainda envia pastas.',
    trustTitle: 'Confiança',
    trustBody:
      'Revê sempre antes de enviar. Sem métricas inventadas. Sem «usado por N empresas».',
    priceTitle: 'Preço',
    priceBody:
      'Preço ainda não está definido. Pode experimentar a aplicação em modo de demonstração, sem cartão.',
    ctaBandTitle: 'Carregue um recibo e veja o pacote',
    ctaBandBody: 'A estimativa de IVA é para revisão. O envio ao contabilista fica sempre consigo.',
    footerContact: 'Contacto — a anunciar',
    footerPrivacy: 'Privacidade',
    footerNote: 'FaturaFlow. Recibos portugueses → IVA → pacote para o contabilista.',
    langLabel: 'EN',
    diagramReceipt: 'Recibo',
    diagramIva: 'IVA',
    diagramPack: 'pasta.zip',
  },
  en: {
    wordmark: 'FaturaFlow',
    navComo: 'How it works',
    navPreco: 'Pricing',
    navEntrar: 'Sign in',
    navComecar: 'Start',
    h1: 'Get receipt VAT ready for your accountant',
    sub: 'Upload Portuguese invoices and receipts. Get a VAT estimate and a tidy pack to send.',
    ctaPrimary: 'Start with a receipt',
    ctaSecondary: 'See how it works',
    howTitle: 'How it works',
    how1Title: 'Upload',
    how1Body: 'PDF or photo',
    how2Title: 'Estimate VAT',
    how2Body: 'Lines and rate when readable',
    how3Title: 'Pack',
    how3Body: 'Files ready for the accountant',
    receiveTitle: 'What you get',
    receive1: 'VAT estimate per document (when readable)',
    receive2: 'An organised document list',
    receive3: 'A pack to forward to your accountant',
    whoTitle: 'Who it is for',
    whoBody:
      'People who still gather receipts by hand and lose time before sending them to the accountant. Micro-businesses, freelancers, and anyone who still sends folders.',
    trustTitle: 'Trust',
    trustBody: 'Always review before you send. No invented metrics. No “used by N companies”.',
    priceTitle: 'Pricing',
    priceBody: 'Pricing is not set yet. You can try the app in demo mode, no card required.',
    ctaBandTitle: 'Upload a receipt and see the pack',
    ctaBandBody: 'The VAT figure is an estimate for review. You decide what to send.',
    footerContact: 'Contact — to be announced',
    footerPrivacy: 'Privacy',
    footerNote: 'FaturaFlow. Portuguese receipts → VAT → accountant pack.',
    langLabel: 'PT',
    diagramReceipt: 'Receipt',
    diagramIva: 'VAT',
    diagramPack: 'folder.zip',
  },
} as const;
