export type LandingLang = 'pt' | 'en';

export const landingCopy = {
  pt: {
    wordmark: 'FaturaFlow',
    navProblema: 'O problema',
    navComo: 'A solução',
    navPreco: 'Preço',
    navEntrar: 'Entrar',
    navComecar: 'Começar',
    h1: 'Pare de descobrir o IVA um dia antes do prazo',
    sub: 'Em Portugal, faturas e recibos acumulam-se em pastas, WhatsApp e gavetas. Muitas vezes só sabe quanto IVA pagar quando o contabilista calcula — quase no limite. O FaturaFlow deixa-o carregar os documentos, ver uma estimativa de IVA com tempo, e enviar um pacote organizado ao contabilista.',
    ctaPrimary: 'Começar com um recibo',
    ctaSecondary: 'Ver como funciona',
    problemTitle: 'O problema',
    problem1Title: 'Documentos no caos',
    problem1Body:
      'Faturas e recibos ficam em papel, no WhatsApp e em pastas. Não há um sítio só.',
    problem2Title: 'IVA de surpresa',
    problem2Body:
      'Muitas vezes só sabe quanto IVA pagar quando o contabilista calcula — por vezes cerca de um dia antes do prazo. O fluxo de caixa fica em risco.',
    problem3Title: 'Tempo perdido antes de enviar',
    problem3Body: 'Antes de enviar, perde tempo a reunir o que está espalhado.',
    howTitle: 'A solução',
    how1Title: 'Carregar',
    how1Body: 'Faturas e recibos portugueses, em PDF ou foto.',
    how2Title: 'Estimar IVA cedo',
    how2Body: 'Uma estimativa de IVA para rever, com tempo antes do prazo.',
    how3Title: 'Pacote',
    how3Body: 'Originais e um resumo, organizados para o contabilista.',
    receiveTitle: 'O que recebe',
    receive1: 'Estimativa de IVA por documento (quando legível)',
    receive2: 'Lista organizada dos documentos',
    receive3: 'Pacote para reenviar ao contabilista',
    whoTitle: 'Para quem',
    whoBody:
      'Quem junta recibos à mão e perde tempo antes de enviar ao contabilista. Micro-empresas, freelancers, e quem ainda envia pastas.',
    trustTitle: 'Confiança',
    trustBody:
      'Revê sempre antes de enviar. Sem métricas inventadas. Sem «usado por N empresas».',
    priceTitle: 'Preço',
    priceBody:
      'Preço ainda não está definido. Pode experimentar a aplicação em modo de demonstração, sem cartão.',
    ctaBandTitle: 'Carregue um recibo e veja o pacote',
    ctaBandBody: 'A estimativa de IVA é para revisão. O envio ao contabilista fica sempre consigo.',
    footerContact: 'Contacto — a anunciar',
    footerPrivacy: 'Privacidade',
    footerNote: 'FaturaFlow. Recibos portugueses → IVA → pacote para o contabilista.',
    langLabel: 'EN',
    diagramReceipt: 'Recibo',
    diagramIva: 'IVA',
    diagramPack: 'pasta.zip',
  },
  en: {
    wordmark: 'FaturaFlow',
    navProblema: 'The problem',
    navComo: 'The solution',
    navPreco: 'Pricing',
    navEntrar: 'Sign in',
    navComecar: 'Start',
    h1: 'Stop learning your VAT the day before it’s due',
    sub: 'In Portugal, invoices and receipts pile up in folders, WhatsApp, and drawers. You often only learn how much VAT to pay when the accountant calculates it — almost at the deadline. FaturaFlow lets you upload the documents, see a VAT estimate with time to spare, and send an organised pack to the accountant.',
    ctaPrimary: 'Start with a receipt',
    ctaSecondary: 'See how it works',
    problemTitle: 'The problem',
    problem1Title: 'Documents in chaos',
    problem1Body:
      'Invoices and receipts sit on paper, in WhatsApp, and in folders. There is no single place.',
    problem2Title: 'VAT as a surprise',
    problem2Body:
      'You often only learn what VAT to pay when the accountant calculates it — sometimes about a day before the deadline. Cash flow is at risk.',
    problem3Title: 'Time lost before you send',
    problem3Body: 'Before you send, you lose time gathering what is scattered.',
    howTitle: 'The solution',
    how1Title: 'Upload',
    how1Body: 'Portuguese invoices and receipts, as PDF or photo.',
    how2Title: 'Estimate VAT early',
    how2Body: 'A VAT estimate to review, with time before the deadline.',
    how3Title: 'Pack',
    how3Body: 'Originals and a summary, organised for the accountant.',
    receiveTitle: 'What you get',
    receive1: 'VAT estimate per document (when readable)',
    receive2: 'An organised document list',
    receive3: 'A pack to forward to your accountant',
    whoTitle: 'Who it is for',
    whoBody:
      'People who still gather receipts by hand and lose time before sending them to the accountant. Micro-businesses, freelancers, and anyone who still sends folders.',
    trustTitle: 'Trust',
    trustBody: 'Always review before you send. No invented metrics. No “used by N companies”.',
    priceTitle: 'Pricing',
    priceBody: 'Pricing is not set yet. You can try the app in demo mode, no card required.',
    ctaBandTitle: 'Upload a receipt and see the pack',
    ctaBandBody: 'The VAT figure is an estimate for review. You decide what to send.',
    footerContact: 'Contact — to be announced',
    footerPrivacy: 'Privacy',
    footerNote: 'FaturaFlow. Portuguese receipts → VAT → accountant pack.',
    langLabel: 'PT',
    diagramReceipt: 'Receipt',
    diagramIva: 'VAT',
    diagramPack: 'folder.zip',
  },
} as const;
