export type LandingLang = 'pt' | 'en';

export const landingCopy = {
  pt: {
    wordmark: "Invoflow",
    navEntrar: "Entrar",
    navComecar: "Começar",
    h1: "Pare de descobrir o IVA um dia antes do prazo",
    sub: "Carregue faturas e recibos portugueses. O IVA estimado aparece com tempo para o preparar.",
    ctaPrimary: "Começar com um recibo",
    exampleKicker: "Exemplo · março de 2026",
    receiptKicker: "Recibo",
    receiptName: "Café Lisboa, Lda",
    receiptMeta: "NIF 514 832 109 · FT 2026/184",
    receiptDate: "12 mar 2026",
    receiptBase: "Base",
    receiptBaseVal: "39,51 €",
    receiptVat: "IVA 23%",
    receiptVatVal: "9,09 €",
    receiptTotal: "Total",
    receiptTotalVal: "48,60 €",
    ivaKicker: "IVA",
    ivaLabel: "Estimado a pagar",
    ivaAmount: "486 €",
    ivaDue: "Prazo 20 de abril",
    ivaDetail: "14 documentos. Este recibo entra com 9,09 €.",
    ivaCaveat:
      "É uma estimativa para rever. Nada é enviado à Autoridade Tributária.",
    packKicker: "Pacote",
    packTitle: "O que segue para o contabilista",
    packFile1: "originais/2026-03-12-cafe-lisboa.pdf",
    packFile2: "resumo.csv",
    packFile3: "resumo.pdf",
    packNote: "O ficheiro original fica intacto.",
    ctaBandTitle: "Carregue um recibo e veja o seu número",
    ctaBandBody:
      "Demonstração, sem cartão. O que enviar ao contabilista decide-o você.",
    footerPrivacy: "Privacidade",
    footerNote:
      "Invoflow. Recibos portugueses → IVA → pacote para o contabilista.",
    langLabel: "EN",
    diagramReceipt: "Recibo",
    diagramIva: "IVA",
    diagramPack: "Pacote",
  },
  en: {
    wordmark: "Invoflow",
    navEntrar: "Sign in",
    navComecar: "Start",
    h1: "Stop learning your VAT the day before it’s due",
    sub: "Upload Portuguese invoices and receipts. The VAT estimate shows up with time to prepare.",
    ctaPrimary: "Start with a receipt",
    exampleKicker: "Example · March 2026",
    receiptKicker: "Receipt",
    receiptName: "Café Lisboa, Lda",
    receiptMeta: "NIF 514 832 109 · FT 2026/184",
    receiptDate: "12 Mar 2026",
    receiptBase: "Net",
    receiptBaseVal: "€39.51",
    receiptVat: "VAT 23%",
    receiptVatVal: "€9.09",
    receiptTotal: "Total",
    receiptTotalVal: "€48.60",
    ivaKicker: "VAT",
    ivaLabel: "Estimated payable",
    ivaAmount: "€486",
    ivaDue: "Due 20 April",
    ivaDetail: "14 documents. This receipt contributes €9.09.",
    ivaCaveat:
      "An estimate to review. Nothing is filed with the tax authority.",
    packKicker: "Pack",
    packTitle: "What goes to the accountant",
    packFile1: "originais/2026-03-12-cafe-lisboa.pdf",
    packFile2: "resumo.csv",
    packFile3: "resumo.pdf",
    packNote: "The original file stays intact.",
    ctaBandTitle: "Upload a receipt and see your number",
    ctaBandBody: "Demo mode, no card. You decide what to send.",
    footerPrivacy: "Privacy",
    footerNote: "Invoflow. Portuguese receipts → VAT → accountant pack.",
    langLabel: "PT",
    diagramReceipt: "Receipt",
    diagramIva: "VAT",
    diagramPack: "Pack",
  },
} as const;
